name: tvm-builder
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: xundaoxd/ml:latest
      env:
        TVM_VERSION: 0.9.0
    steps:
      - name: Compile
        run: |
          wget -O- https://dlcdn.apache.org/tvm/tvm-v${TVM_VERSION}/apache-tvm-src-v${TVM_VERSION}.tar.gz | tar -C /tmp -xvz
          (cd /tmp/apache-tvm-src-v${TVM_VERSION} \
            && mkdir build && cp cmake/config.cmake build \
            && sed -i 's/set(USE_CUDA OFF)/set(USE_CUDA ON)/;s/set(USE_CUDNN OFF)/set(USE_CUDNN ON)/;s/set(USE_LLVM OFF)/set(USE_LLVM ON)/' build/config.cmake \
            && cmake -B build && cmake --build build -j $(cat /proc/cpuinfo | grep processor | wc -l) \
            && cd python && python setup.py bdist_wheel)
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: tvm
          path: /tmp/apache-tvm-src-v${TVM_VERSION}/python/dist/
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: /tmp/apache-tvm-src-v${TVM_VERSION}/python/dist/*.whl

